[package]
name = "arbitrary-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ziggy = { path = "../../", default-features = false }
arbitrary = { version = "1", features= ["derive"] }
